/**
 * OpenRouter 汉化词库(简体中文)
 *
 * 实现方式参考 https://github.com/maboloshi/github-chinese
 *
 * 词库结构说明:
 *   I18N.conf            全局配置(忽略规则等)
 *   I18N['zh-CN']        简体中文字典
 *     public            公共词条(所有页面通用)
 *     home / models / model / chat / rankings / apps / docs /
 *     settings / signin / blog / misc   按页面类型区分的词条
 *
 * 词条格式:
 *   static  静态词典,精确匹配(文本会先去除首尾空白、合并多余空白)
 *   regexp  正则规则,格式为 [正则表达式, 替换文本] 的数组
 *   title   页面标题词条,同样分为 static 和 regexp
 *
 * 页面类型检测规则见 main.user.js 的 detectPageType() 函数。
 */
'use strict';

const I18N = {
  /* ============================ 全局配置 ============================ */
  conf: {
    // 全局与页面特定忽略选择器:命中这些选择器的元素及其子树不参与翻译
    ignoreSelectorPage: {
      '*': [
        'script',
        'style',
        'noscript',
        'svg',
        'img',
        'canvas',
        'video',
        'audio',
        'code',
        'pre',
        'kbd',
        'samp',
        'textarea',                            // 文本输入区域
        '[contenteditable="true"]',            // 可编辑内容
        '[class*="font-mono"]',                // 等宽字体(代码/密钥等)
        '[data-testid="composer-input"]',      // 聊天输入框
      ],
      chat: [
        '[data-testid="playground-reasoning-panel"]', // 推理过程展示
      ],
      docs: [
        '[class*="code-block"]',
        '[class*="copy-code-button"]',
      ],
    },
    // 仅当这些选择器内的 DOM 发生变化时忽略重新翻译(用于避免影响流式输出的内容)
    ignoreMutationSelectorPage: {
      '*': [],
      chat: [
        '[data-testid="playground-chat-pane"]', // 聊天消息区域(AI 流式回复)
      ],
    },
    // 这些页面的文本节点变化时也要进行翻译(React 原地更新文本的场景)
    characterDataPage: ['chat', 'model', 'docs', 'rankings', 'models', 'workspaces', 'settings', 'activity', 'logs'],
  },

  /* ============================ 简体中文 ============================ */
  'zh-CN': {
    /* ---------------------------- 公共词条 ---------------------------- */
    public: {
      static: {
        // 主导航
        'Home': '首页',
        'Models': '模型',
        'Fusion': '融合',
        'Chat': '聊天',
        'Rankings': '排行榜',
        'Apps': '应用',
        'Docs': '文档',
        'Discover': '发现',
        'Providers': '提供商',
        'Pricing': '定价',
        'Enterprise': '企业版',
        'Labs': '实验室',
        'Search': '搜索',
        'Sign Up': '注册',
        'Sign up': '注册',
        'Sign In': '登录',
        'Sign in': '登录',
        'Sign out': '退出登录',
        'Skip to content': '跳转到内容',
        'Skip to main content': '跳转到主要内容',
        'Open navigation menu': '打开导航菜单',
        'Notifications': '通知',

        // 登录后侧边栏(工作区导航)
        'Personal': '个人',
        'Default Workspace': '默认工作区',
        'Overview': '概览',
        'Guardrails': '护栏',
        'BYOK': '自带密钥',
        'Routing': '路由',
        'Presets': '预设',
        'Plugins': '插件',
        'Observability': '可观测性',
        'Classifiers': '分类器',
        'Account': '账户',
        'Profile': '个人资料',
        'Logs': '日志',
        'Management Keys': '管理密钥',
        'Preferences': '偏好设置',
        'Keys': '密钥',
        'Workspaces': '工作区',
        'Workspace': '工作区',
        'Chatroom': '聊天室',
        'Unknown': '未知',
        'Explore': '探索',
        'Spend': '花费',
        'Total': '总计',
        'TOTAL': '总计',
        'Prompt': '提示词',
        'Completion': '补全',
        'Reasoning': '推理',

        // 模态分类标签(大写形式,出现在模型列表/排行榜页签)
        'Text': '文本',
        'Image': '图像',
        'Embeddings': '向量嵌入',
        'Audio': '音频',
        'Video': '视频',
        'Rerank': '重排序',
        'Speech': '语音',
        'Transcription': '转录',
        'providers': '提供商',
        'by': '来自',
        'All models': '所有模型',
        'new': '新',
        'Token': 'Token 数',
        'quantization': '量化',
        'Requests': '请求数',
        'Images': '图像',
        'Duration': '时长',
        'Voice': '音色',
        'Seconds': '秒数',
        'Size': '尺寸',
        'Chars': '字符数',
        'Preview': '预览',
        'Supported': '已支持',
        'Values': '值',
        'Parameter': '参数',
        'Model weights': '模型权重',
        'Filter quantization': '筛选量化',
        'Image Outputs': '图像输出',
        'Image Inputs': '图像输入',
        'Image References': '图像参考',
        'Aspect Ratio': '宽高比',
        'First Frame': '首帧',
        'Last Frame': '尾帧',
        'Audio output': '音频输出',
        'Full size': '完整尺寸',
        'Video + audio': '视频 + 音频',
        'Video only': '仅视频',
        'Transcribed Characters': '转录字符数',
        'Generate an image': '生成图像',
        'Use the dedicated Image API with': '使用专门的图像 API',
        'Sign in to generate': '登录后生成',
        'Sign in to Transcribe': '登录后转录',
        'Transcribe with timestamps': '带时间戳转录',
        'Transcribe with speaker labels': '带说话人标签转录',
        'Summarize after transcribing': '转录后总结',
        'Drop an audio file or click to browse': '拖入音频文件或点击浏览',
        'Supports WAV, MP3, M4A, FLAC, OGG, WebM, AAC': '支持 WAV、MP3、M4A、FLAC、OGG、WebM、AAC',
        '(opens in new tab)': '(在新标签页中打开)',
        'Supported Parameters': '支持的参数',
        'Provider Passthrough Parameters': '提供商透传参数',
        'Provider-specific keys accepted under': '接受的提供商特定键:',
        'Arena Rank': '竞技场排名',
        'Arena Appearances': '竞技场出场次数',
        'Category Performance': '分类表现',
        'Elo': 'Elo 积分',
        'Overall Text to Video Arena': '整体文生视频竞技场',
        'Overall Text to Speech Arena': '整体文生语音竞技场',
        'Evaluation Results': '评测结果',
        'Reasoning Performance': '推理性能',
        'Blog Post': '博客文章',
        'launch announcement': '发布公告',
        'docs here': '此处文档',
        'user guide': '用户指南',
        'Learn more in our docs': '更多信息请参阅我们的文档',
        'Learn more about image generation': '了解图像生成',
        'Learn more about video generation': '了解视频生成',
        'Learn more about reasoning tokens': '了解推理 Token',
        'Click here to learn more about this model': '点击此处了解更多关于此模型的信息',
        'Note that BYOK is required for this model. Set up here:': '注意:此模型需要使用自带密钥 (BYOK)。在此设置:',
        'offline chat model': '离线聊天模型',
        'online version': '在线版本',
        'Read more on the': '更多信息请阅读',
        'image_config API Parameter': 'image_config API 参数',
        'Reasoning API parameter': '推理 API 参数',
        'Throughput percentiles on OpenRouter': 'OpenRouter 上的吞吐量百分位数',
        'Latency percentiles on OpenRouter': 'OpenRouter 上的延迟百分位数',
        'End-to-End Latency percentiles on OpenRouter': 'OpenRouter 上的端到端延迟百分位数',
        'This model is hosted by one provider. OpenRouter forwards every request to it directly — no routing decisions to make.': '此模型仅由一个提供商托管。OpenRouter 会将每个请求直接转发给它——无需做路由决策。',
        'Enter to generate · Shift+Enter for a new line': '回车生成 · Shift+回车换行',
        'Speech-to-text transcript characters returned by this model per day on OpenRouter.': '此模型每天在 OpenRouter 上返回的语音转文字转录字符数。',
        'Total length of video generated by this model per day on OpenRouter, shown in hours.': '此模型每天在 OpenRouter 上生成的视频总时长，以小时显示。',
        'Total number of API requests made to this model per day on OpenRouter.': '此模型每天在 OpenRouter 上的 API 请求总数。',
        'Image inputs count visual attachments processed in prompts. Image outputs count generated images. Some requests may process or generate multiple images.': '图像输入统计提示词中处理的视觉附件数量。图像输出统计生成的图像数量。某些请求可能处理或生成多张图像。',
        'Send a prompt and receive generated images as base64-encoded data.': '发送提示词，接收以 base64 编码返回的生成图像。',
        'OpenRouter supports reasoning-enabled models that can show their step-by-step thinking process. Use the': 'OpenRouter 支持可显示逐步思考过程的推理模型。在请求中使用',
        'parameter in your request to enable reasoning, and access the': '参数启用推理，并通过',
        'array in the response to see the model\'s internal reasoning before the final answer. When continuing a conversation, preserve the complete': '数组查看最终回答前的模型内部推理。继续对话时，请保留完整的',
        'when passing messages back to the model so it can continue reasoning from where it left off.': '消息传回模型，以便它可以从上次停下的地方继续推理。',
        'Submits a video generation request and returns a polling URL to check status': '提交视频生成请求，并返回用于查询状态的轮询 URL',
        'Submits an image generation request. Returns base64-encoded images or streams partial results via SSE.': '提交图像生成请求。返回 base64 编码的图像，或通过 SSE 流式返回部分结果。',
        'Submits a rerank request to the rerank router': '向重排序路由器提交重排序请求',
        'Submits an embedding request to the embeddings router': '向嵌入路由器提交嵌入请求',
        'Transcribes audio into text. Accepts base64-encoded audio input and returns the transcribed text.': '将音频转录为文本。接受 base64 编码的音频输入，并返回转录文本。',
        'Synthesizes audio from the input text. Returns a raw audio bytestream in the requested format (e.g. mp3, pcm, wav).': '根据输入文本合成音频。以请求的格式(如 mp3、pcm、wav)返回原始音频字节流。',
        'OpenRouter provides a speech-to-text API that transcribes audio into text. Send base64-encoded audio with a model, and receive the transcribed text in JSON.': 'OpenRouter 提供将音频转录为文本的语音转文字 API。将 base64 编码的音频与模型一起发送，即可在 JSON 中收到转录文本。',
        'The generation ID is returned in the': '生成 ID 会在',
        'response header for tracking.': '响应头中返回，用于跟踪。',
        'OpenRouter provides a text-to-speech API that converts text into natural-sounding audio. Send text and a voice selection, and receive raw audio bytes in your chosen format.': 'OpenRouter 提供将文本转换为自然语音的文本转语音 API。发送文本和音色选择，即可收到所选格式的原始音频字节。',
        'The response is a raw audio stream (not JSON). The generation ID is returned in the': '响应是原始音频流(非 JSON)。生成 ID 会在',
        'OpenRouter provides a rerank API that reorders documents by relevance to a query. Pass a query and a list of documents, and the model returns them ranked by relevance score.': 'OpenRouter 提供按与查询的相关性对文档重新排序的重排序 API。传入查询和文档列表，模型会按相关性得分返回排序结果。',
        'OpenRouter provides an OpenAI-compatible embeddings API that you can call directly, or using the OpenAI SDK.': 'OpenRouter 提供兼容 OpenAI 的嵌入 API，您可以直接调用，或使用 OpenAI SDK。',
        'This setting aims to control the repetition of tokens based on how often they appear in the input.': '此设置旨在根据 Token 在输入中出现的频率来控制重复。',
        'Adjusts how often the model repeats specific tokens already used in the input.': '调整模型重复输入中已使用过的特定 Token 的频率。',
        'Helps to reduce the repetition of tokens from the input.': '有助于减少输入中 Token 的重复。',
        'Represents the minimum probability for a token to be considered, relative to the probability of the most likely token.': '表示 Token 被考虑的最低概率，相对于最可能 Token 的概率。',
        'Accepts a JSON object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100.': '接受一个 JSON 对象，将 Token(由其分词器中的 Token ID 指定)映射到 -100 到 100 之间的偏置值。',
        'Whether to return log probabilities of the output tokens or not.': '是否返回输出 Token 的对数概率。',
        'An integer between 0 and 20 specifying the number of most likely tokens to return at each token position, each with an associated log probability.': '一个 0 到 20 之间的整数，指定在每个 Token 位置返回的最可能 Token 数量，每个都带有相应的对数概率。',
        'Configures native web search options for models and providers that support web-connected answers.': '为支持联网回答的模型和提供商配置原生网络搜索选项。',
        'If specified, the inferencing will sample deterministically, such that repeated requests with the same seed and parameters should return the same result.': '如果指定，推理将确定性采样，使用相同种子和参数的重复请求应返回相同结果。',

        // 视频竞技场分类
        '3D animation': '3D 动画',
        'Abstract': '抽象',
        'Action': '动作',
        'Animals': '动物',
        'Buildings': '建筑',
        'Cartoon and anime': '卡通与动漫',
        'Fantasy': '奇幻',
        'Fashion': '时尚',
        'Food': '食物',
        'Indoor': '室内',
        'Long prompt': '长提示词',
        'Moving camera': '移动镜头',
        'Nature': '自然',
        'Outdoor': '户外',
        'People': '人物',
        'Photorealistic': '写实',
        'Physics': '物理',
        'Sci Fi': '科幻',
        'Screens': '屏幕',
        'Short prompt': '短提示词',
        'Specific lighting': '特定光照',
        'Specific location or era': '特定地点或时代',
        'Sports': '运动',
        'Technology': '科技',
        'Transport': '交通',
        'Water': '水',
        'Weather and effects': '天气与特效',

        // 退出登录(头像菜单)
        'Sign Out': '退出登录',
        'Log Out': '退出登录',
        'Logout': '退出登录',
        'Log out': '退出登录',

        // 通用界面元素
        'View more': '查看更多',
        'View more →': '查看更多 →',
        'Model Filters': '模型筛选',
        'Quick Start': '快速开始',
        'Get your API key': '获取您的 API 密钥',
        'Frequently asked questions': '常见问题',
        'Previous slide': '上一张',
        'Next slide': '下一张',
        'Sign in to try this model': '登录后试用此模型',
        'Get Code': '获取代码',
        'Raw': '原始',
        'Quality': '质量',
        'Budget': '预算',
        'Fast': '快速',
        'Custom': '自定义',
        'Runs': '运行记录',
        'beta': '测试版',
        'Today': '今天',
        'More models from': '更多模型来自',
        'Parameters': '参数',

        // 页脚
        'Product': '产品',
        'Company': '公司',
        'Developer': '开发者',
        'Connect': '社区',
        'About': '关于',
        'Blog': '博客',
        'Careers': '招聘',
        'Hiring': '正在招聘',
        'Privacy': '隐私',
        'Terms of Service': '服务条款',
        'Support': '支持',
        'Works With OR': '与 OpenRouter 合作',
        'Data': '数据',
        'Documentation': '文档',
        'API Reference': 'API 参考',
        'Developer Platform': '开发者平台',
        'Status': '状态',
        'Dashboard': '仪表盘',

        // 通用操作
        'Cancel': '取消',
        'Close': '关闭',
        'Confirm': '确认',
        'OK': '确定',
        'Continue': '继续',
        'Done': '完成',
        'Save': '保存',
        'Save changes': '保存更改',
        'Saved!': '已保存!',
        'Submit': '提交',
        'Apply': '应用',
        'Update': '更新',
        'Create': '创建',
        'Add': '添加',
        'Edit': '编辑',
        'Delete': '删除',
        'Remove': '移除',
        'Rename': '重命名',
        'Copy': '复制',
        'Copied': '已复制',
        'Copy code': '复制代码',
        'Share': '分享',
        'Download': '下载',
        'Upload': '上传',
        'Import': '导入',
        'Export': '导出',
        'Refresh': '刷新',
        'Retry': '重试',
        'Try again': '重试',
        'Back': '返回',
        'Previous': '上一页',
        'Next': '下一页',
        'View all': '查看全部',
        'View': '查看',
        'Open': '打开',
        'Show more': '显示更多',
        'Show less': '收起',
        'Show all': '显示全部',
        'Learn more': '了解更多',
        'Read more': '阅读更多',
        'Browse all': '浏览全部',
        'Browse Models': '浏览模型',
        'Go Home': '返回首页',
        'New': '新',
        'Reset': '重置',
        'Clear': '清空',
        'Enable': '启用',
        'Disable': '禁用',
        'Enabled': '已启用',
        'Disabled': '已禁用',
        'Loading...': '加载中...',
        'Loading': '加载中',
        'Error': '错误',
        'Failed': '失败',
        'Success': '成功',
        'Something went wrong': '出现问题',
        'Not Found': '未找到',
        'Page not found': '页面未找到',
        '404: Not Found': '404: 未找到',
        'Yes': '是',
        'No': '否',

        // 通用表单
        'Email': '邮箱',
        'Email address': '邮箱地址',
        'Password': '密码',
        'Name': '名称',
        'Date': '日期',
        'Status': '状态',
        'Type': '类型',
        'Description': '描述',
        'Amount': '金额',
        'Actions': '操作',
        'Search...': '搜索...',
        'All': '全部',
        'None': '无',
        'Optional': '可选',
        'Required': '必填',
        'Filter': '筛选',
        'Filters': '筛选条件',
        'Reset Filters': '重置筛选',
        'Compare': '对比',
        'List': '列表',
        'Table': '表格',
        'Newest': '最新',
        'Sort': '排序',
        'Sort by': '排序方式',

        // 模型通用
        'Model': '模型',
        'Models': '模型',
        'model': '模型',
        'models': '模型',
        'Provider': '提供商',
        'Context': '上下文',
        'Context length': '上下文长度',
        'Input': '输入',
        'Output': '输出',
        'Price': '价格',
        'Pricing': '定价',
        'Latency': '延迟',
        'Throughput': '吞吐量',
        'Benchmarks': '基准测试',
        'Tokens': 'Token 数',
        'tokens': 'Token',
        'Tokens used': 'Token 用量',
        'Max output': '最大输出',
        'Max tokens': '最大 Token 数',
        'System prompt': '系统提示词',
        'Tool Calling': '工具调用',
        'Tool Calls': '工具调用',
        'Tool calling': '工具调用',
        'Structured Outputs': '结构化输出',
        'Structured outputs': '结构化输出',
        'JSON mode': 'JSON 模式',
        'Architecture': '架构',
        'License': '许可证',
        'Open source': '开源',
        'Quantization': '量化',
        'Creator': '创建者',
        'Params': '参数量',
        'Release date': '发布日期',
        'Released': '发布时间',
        'Endpoint': '端点',
        'API': 'API',
        'API Key': 'API 密钥',
        'API Keys': 'API 密钥',
        'API key': 'API 密钥',
        'Get API Key': '获取 API 密钥',
        'Modalities': '模态',
        'Input Modalities': '输入模态',
        'Free': '免费',
        'Beta': '测试版',
        'Experimental': '实验性',
        'Deprecated': '已弃用',
        'Featured': '精选',
        'Popular': '热门',
        'Trending': '趋势',
        'Weekly Trend': '周趋势',
        'New chat': '新聊天',
        'Untitled': '未命名',
        'Select a model': '选择模型',
        'Choose a model': '选择模型',
        'Send': '发送',
        'Stop': '停止',
        'Regenerate': '重新生成',
        'Reasoning': '推理',
        'Assistant': '助手',

        // 设置/账户通用
        'Settings': '设置',
        'Account': '账户',
        'Profile': '个人资料',
        'Usage': '用量',
        'Credits': '额度',
        'Balance': '余额',
        'Add credits': '添加额度',
        'Buy credits': '购买额度',
        'Keys': '密钥',
        'Limits': '限制',
        'Billing': '账单',
        'Organization': '组织',
        'Members': '成员',
        'Activity': '活动记录',
        'Security': '安全',
        'Preferences': '偏好设置',
        'Language': '语言',
        'Theme': '主题',
        'Light': '浅色',
        'Dark': '深色',
        'System': '跟随系统',
        'Monthly': '每月',
        'Daily': '每日',
        'Yearly': '每年',
        'Plan': '套餐',
        'Pro': '专业版',
        'Team': '团队版',
        'Pay as you go': '按量付费',

        // 账户验证弹窗
        'Verify your email': '验证您的邮箱',
        'We could not find a primary email address on your account. Please contact support.': '我们无法在您的账户中找到主邮箱地址。请联系支持。',
        'Send code': '发送验证码',
        'Confirmation required': '需要确认',
        'Please confirm the following to continue:': '请确认以下内容以继续:',
        'You can review this anytime in': '您可以随时在',
        'settings': '设置',
        'Confirmed': '已确认',

        // 额度不足弹窗
        'Insufficient credits': '额度不足',
        'Add credits to continue using paid models.': '添加额度以继续使用付费模型。',
        'Continue with free models': '继续使用免费模型',
        'or': '或',

        // 设置页通用
        'Create': '创建',
        'Manage': '管理',
        'User': '用户',
        'Organization': '组织',
        'New Key': '新建密钥',
        'Create API Key': '创建 API 密钥',
        'Expires': '过期时间',
        'Expiration': '有效期',
        'Last Used': '最后使用',
        'No expiration': '永不过期',
        'Never expires': '永不过期',
        'Key usage': '密钥用量',
        'Key limit': '密钥上限',
        'Credit limit (optional)': '额度上限(可选)',
        'Reset limit every...': '重置上限周期...',
        'No guardrails': '无护栏',
        'unlimited': '无限制',
        'N/A': '不适用',
        'Active': '生效中',
        'Disabled': '已禁用',
        'Hint': '提示',
        'Name': '名称',
        'Created': '创建时间',
        'No prior data': '暂无数据',
        'Active keys': '生效中的密钥',
        'Disabled / expired': '已停用 / 已过期',
        'Last created': '最近创建',
        'Date Format': '日期格式',
        'How dates appear in logs and activity tables.': '日志和活动记录表格中日期的显示方式。',
        'Default Preset': '默认预设',
        'Default preset for new messages in the chatroom.': '聊天室中新消息的默认预设。',
        'Default': '默认',
        'None': '无',
        'Dismiss': '知道了',
        'Show All': '显示全部',
        'Show more': '显示更多',
        'Less': '更少',
        'More': '更多',
        'Total available': '可用总额',
        'Pay-as-you-go balance': '按量付费余额',
        'Buy Credits': '购买额度',
        'Add Credits': '添加额度',
        'View Usage': '查看用量',
        'View Activity': '查看活动记录',
        'Redeem Promo Code': '兑换优惠码',
        'Auto Top-Up': '自动充值',
        'Use crypto': '使用加密货币',
        'Recent Transactions': '最近交易',
        'History': '历史记录',
        'Need enterprise billing options?': '需要企业账单选项?',
        'Contact sales': '联系销售',
        'Receipt': '收据',
        'Refund': '退款',
        'Get invoice': '获取发票',
        'transaction': '交易',
        'Enable auto top up': '启用自动充值',
        'Payment Methods': '支付方式',
        'Add Payment Method': '添加支付方式',
        'Selected Payment Methods': '已选支付方式',
        'Primary': '主要',
        'When credits are below:': '当额度低于:',
        'Purchase this amount:': '购买金额:',
        'Automatically purchase credits when your balance is below a certain threshold. You can select multiple payment methods that will be tried in order if payment fails.': '当余额低于某个阈值时自动购买额度。您可以选择多个支付方式，如果支付失败将按顺序尝试。',
        'Select up to 3 payment methods. The primary will be tried first, then backups in order if payment fails.': '最多选择 3 个支付方式。优先使用主支付方式，如果支付失败将按顺序尝试备用方式。',
        'Create and manage your API keys.': '创建和管理您的 API 密钥。',
        'Enable analytics cookies': '启用分析 Cookie',
        'Allow analytics cookies to help us improve the user experience and site performance.': '允许使用分析 Cookie 帮助我们改进用户体验和网站性能。',
        'Low Balance Alerts': '低余额提醒',
        'Emails sent to': '邮件发送至',
        'Chat Completion Notifications': '聊天完成通知',
        'Browser notifications when chat responses complete (only when tab is not focused)': '聊天回复完成时的浏览器通知(仅在标签页未聚焦时)',
        'Attestations': '声明',
        '18+ age confirmation': '18 岁以上确认',
        'I confirm that I am 18 years of age or older.': '我确认我已年满 18 岁。',
        'Your chat history in the': '您在',
        'is always stored locally on your device.': '中的聊天历史始终存储在您的设备本地。',
        'Manage your login credentials, security settings, or delete your account.': '管理您的登录凭据、安全设置或删除您的账户。',
        'Create and manage your organization.': '创建和管理您的组织。',
        'Account Type': '账户类型',
        'Your current account tier.': '您当前的账户层级。',
        'Self Serve': '自助服务',
      },
      regexp: [
        // 统计数字,如 "400+ Models" -> "400+ 模型"、"10M+ Users" -> "10M+ 用户"
        [/^(\d[\d.,]*\+?)\s*(models|users|providers|tokens)$/i, (match, num, unit) => {
          const unitMap = { models: '模型', users: '用户', providers: '提供商', tokens: 'Token' };
          return num + ' ' + (unitMap[unit.toLowerCase()] || unit);
        }],
        // 带数量的标签,如 "2 keys"、"0 rooms"、"1 guardrail"、"1 management key"
        [/^(\d+)\s*keys?$/, '$1 个密钥'],
        [/^(\d+)\s*rooms?$/, '$1 个房间'],
        [/^(\d+)\s*guardrails?$/, '$1 个护栏'],
        [/^(\d+)\s*management keys?$/, '$1 个管理密钥'],
        [/^(\d+)\s*models?$/, '$1 个模型'],
        [/^(\d+)\s*workspaces?$/, '$1 个工作区'],
        // "Show 57 more" 等
        [/^Show (\d+) more$/, '显示另外 $1 个'],
        [/^(\d+) featured models matched$/, '$1 个精选模型匹配'],
        // 邮箱验证弹窗,如 "Verify datou_1996@163.com to continue."
        [/^Verify (\S+@\S+) to continue\.$/, '验证 $1 以继续。'],
        // 时间窗口按钮
        [/^1d$/, '1 天'],
        [/^1w$/, '1 周'],
        [/^1mo$/, '1 个月'],
        [/^3mo$/, '3 个月'],
        [/^6mo$/, '6 个月'],
        [/^1y$/, '1 年'],
        // 折扣徽章,如 "90% off"
        [/^(\d+)% off$/, '$1% 折扣'],
        // 价格,如 "$0.95/M input"、"$4/M output"(与 "tokens" 拆分显示的情况)
        [/^\$[\d.]+\/M\s*(input|output)$/, (match, p) => match.replace(/(input|output)$/, p === 'input' ? '输入' : '输出')],
        // 上下文长度,如 "262K context"、"1M context"
        [/^([\d.]+[KM]?)\s*context$/, '$1 上下文'],
        // 模型分类标签,如 "Programming (#39)"
        [/^(Programming|Finance|Health|Science|Technology|General|Vision|Coding|Reasoning|Creative|Writing|Math|Language|Translation|Agentic|Audio|Image|Video|Knowledge|Roleplay|Travel|Legal|Medical|Data|Business) \(#(\d+)\)$/, (match, cat, num) => ({
          Programming: '编程', Finance: '金融', Health: '健康', Science: '科学', Technology: '科技',
          General: '通用', Vision: '视觉', Coding: '编码', Reasoning: '推理', Creative: '创意',
          Writing: '写作', Math: '数学', Language: '语言', Translation: '翻译', Agentic: '智能体',
          Audio: '音频', Image: '图像', Video: '视频', Knowledge: '知识', Roleplay: '角色扮演',
          Travel: '旅行', Legal: '法律', Medical: '医疗', Data: '数据', Business: '商业'
        }[cat] || cat) + ' (#' + num + ')'],
        // 分页,如 "1–20 of 60"
        [/^(\d+)[–-](\d+) of (\d+)$/, '$1–$2 / 共 $3 条'],
        // 运行次数,如 "0 runs"
        [/^(\d+)\s*runs?$/, '$1 次运行'],
        // 示例数,如 "1 example"
        [/^(\d+)\s*examples?$/, '$1 个示例'],
        // 提供商数量,如 "+21 more providers"
        [/^\+(\d+) more providers$/, '另外 $1 个提供商'],
        // 竞技场排名,如 "Top 65%"
        [/^Top (\d+)%$/, '前 $1%'],
        // 竞技场对决数,如 "7274 matches"
        [/^([\d,]+)\s*matches$/, '$1 场对决'],
        // 竞技场对战,如 "22,862 tournaments"
        [/^([\d,]+)\s*tournaments$/, '$1 场对战'],
        // 胜率,如 "51.0% Win"
        [/^([\d.]+)%\s*Win$/, '$1% 胜率'],
        // 平均时长,如 "66.5s Avg"
        [/^([\d.]+)s\s*Avg$/, '$1s 平均'],
      ],
      title: {
        static: {},
        regexp: [],
      },
    },

    /* ------------------------------ 首页 ------------------------------ */
    home: {
      static: {
        'The Unified Interface For LLMs': '大语言模型统一接口',
        // hero 副标题被内联元素拆分为多个文本节点
        'Better': '更优',
        'prices': '价格',
        ', better': '，更优',
        'uptime': '可用性',
        ', no subscriptions.': '，无需订阅。',
        // 统计数字碎片("400+ active models on 70+ providers" 的拆分节点)
        'active models on': '个活跃模型，分布在',
        '250k+ apps using OpenRouter with 4.2M+ users globally': '全球 25 万+ 应用通过 OpenRouter 服务 420 万+ 用户',
        'Credits can be used with any model or provider.': '额度可用于任何模型或提供商。',
        'Discover Models': '发现模型',
        'Monthly Tokens': '月度 Token 数',
        'Global Users': '全球用户',
        'One API for Any Model': '一个 API 接入所有模型',
        'Access all major models through a single, unified interface. OpenAI SDK works out of the box.': '通过单一统一接口访问所有主流模型。OpenAI SDK 开箱即用。',
        'Higher Availability': '更高的可用性',
        'Reliable AI models via our distributed infrastructure. Fall back to other providers when one goes down.': '通过我们的分布式基础设施提供可靠的 AI 模型。当某个提供商宕机时，自动切换到其他提供商。',
        'Price and Performance': '价格与性能',
        'Keep costs in check without sacrificing speed. OpenRouter runs at the edge for minimal latency between your users and their inference.': '在不牺牲速度的前提下控制成本。OpenRouter 在边缘运行，最大限度缩短您的用户与推理之间的延迟。',
        'Custom Data Policies': '自定义数据策略',
        'Protect your organization with fine grained data policies. Ensure prompts only go to the models and providers you trust.': '通过细粒度的数据策略保护您的组织。确保提示词只发送给您信任的模型和提供商。',
        'View docs': '查看文档',
        'Featured Models': '精选模型',
        'Featured Agents': '精选智能体',
        'Featured Apps': '精选应用',
        'View all': '查看全部',
        'The easiest way to go from idea to app': '从创意到应用的最简单方式',
        'An autonomous agent that grows with you': '与您共同成长的自主智能体',
        'Everything you need for agentic development': '智能体开发所需的一切',
        'Signup': '注册',
        'Create an account to get started. You can set up an org for your team later.': '创建账户开始使用。您之后可以为团队设置组织。',
        'Create an account': '创建账户',
        'Create an API key and start making requests.': '创建 API 密钥并开始发起请求。',
        'Fully OpenAI compatible': '完全兼容 OpenAI',
        'Recent Blog Posts': '最新博客文章',
        'Weekly Trend': '周趋势',
        'by': '来自',
        'Google': 'Google',
        'MetaMask': 'MetaMask',
        'Hiring': '正在招聘',
        'Enter your prompt': '输入您的提示词',
      },
      regexp: [],
      title: {
        static: {},
        regexp: [],
      },
    },

    /* ---------------------------- 模型列表页 ---------------------------- */
    models: {
      static: {
        'Discover Models': '发现模型',
        'Compare AI Models': '对比 AI 模型',
        'File': '文件',
        'Prompt pricing': '提示词定价',
        'Output pricing': '输出定价',
        'Series': '系列',
        'Categories': '类别',
        'Supported Parameters': '支持的参数',
        'Distillable': '可蒸馏',
        'Zero Data Retention': '零数据保留',
        'In-Region Routing': '区域内路由',
        'Model age': '模型年龄',
        'Inactive Models': '非活跃模型',
        'Model Authors': '模型作者',
        'Artificial Analysis': 'Artificial Analysis',
        'Design Arena': 'Design Arena',
        'context': '上下文',
        'input': '输入',
        'output': '输出',
        'Features': '功能',
        'Filter by': '按条件筛选',
        'Showing': '显示',
        'of': '共',
        'results': '条结果',
        'No models found': '未找到模型',
        'Try adjusting your filters': '尝试调整您的筛选条件',
      },
      regexp: [
        // 价格行,如 "$0.95/M input tokens" -> "$0.95/M 输入 Token"
        [/^\$[\d.]+\/M\s*(input|output)\s*tokens$/, (match, p1) => match.replace(/(input|output)\s*tokens$/, p1 === 'input' ? '输入 Token' : '输出 Token')],
      ],      title: {
        static: {
          'Compare AI Models: Pricing, Context & Benchmarks | OpenRouter': '对比 AI 模型:价格、上下文与基准测试 | OpenRouter',
        },
        regexp: [],
      },
    },

    /* ---------------------------- 模型详情页 ---------------------------- */
    model: {
      static: {
        'Compare': '对比',
        'Playground': '试玩台',
        'Try this model': '试试这个模型',
        'In / Out Price': '输入 / 输出价格',
        'In / Out': '输入 / 输出',
        'per 1M': '每 1M',
        'Knowledge Cutoff': '知识截止日期',
        'Performance': '性能',
        'Uptime': '可用性',
        'FAQ': '常见问题',
        'Standard': '标准',
        'Latency / throughput': '延迟 / 吞吐量',
        'P50': 'P50',
        'Cache read': '缓存读取',
        'Weighted Average': '加权平均值',
        'Weighted Avg Input Price': '加权平均输入价格',
        'Weighted Avg Output Price': '加权平均输出价格',
        '/M tokens': '/M Token',
        'Price History': '价格历史',
        'Effective': '实际',
        'Listed': '标价',
        '1W': '1 周',
        '3M': '3 月',
        '1Y': '1 年',
        'Chart visibility': '图表显示',
        'Effective in': '实际输入',
        'Effective out': '实际输出',
        'Listed in': '标价输入',
        'Listed out': '标价输出',
        'Cache hit rate': '缓存命中率',
        'Token share': 'Token 占比',
        '1d': '1 天',
        '1 week': '1 周',
        'Avg': '平均',
        'tok/s': 'tok/s',
        'E2E Latency': '端到端延迟',
        'AutoExacto Benchmarks': 'AutoExacto 基准测试',
        'auto-routing': '自动路由',
        'Tool Call Error Rate': '工具调用错误率',
        'Structured Output Error Rate': '结构化输出错误率',
        'Cache Hit Rate': '缓存命中率',
        'Avg. Provider Uptime (3d)': '提供商平均可用性 (3 天)',
        'averaged across all endpoints': '所有端点平均值',
        'Avg. OpenRouter Uptime (3d)': 'OpenRouter 平均可用性 (3 天)',
        'averaged across all requests': '所有请求平均值',
        'Endpoints API': '端点 API',
        'How Design Arena works': 'Design Arena 工作原理',
        'Ranking Distribution': '排名分布',
        'Description': '描述',
        'Examples': '示例',
        'Chat template': '聊天模板',
        'Supports': '支持',
        'Format': '格式',
        'Image input': '图像输入',
        'System prompt': '系统提示词',
        'Temperature': '温度',
        'Top P': 'Top P',
        'Top K': 'Top K',
        'Stop sequences': '停止序列',
        'Seed': '随机种子',
        'Stream': '流式输出',
        'Add to chat': '添加到聊天',
        'Run in playground': '在试玩台运行',
        'Open in chat': '在聊天中打开',
        'View more': '查看更多',
        'View less': '收起',
        'Show more': '显示更多',
        'The average price customers actually pay for this model, next to the prices providers post. Caching and discounts mean the price actually paid is often well below the listed one.': '这是客户实际支付的平均价格，旁边是提供商公布的价格。缓存与折扣意味着实际支付的价格通常远低于标价。',
        'Throughput is how fast the model writes (tokens per second — higher is better). Latency is total round-trip time (lower is better). TTFT is time-to-first-token — how long before you see anything appear (lower is better).': '吞吐量是模型生成的速度(Token/秒，越高越好)。延迟是完整的往返时间(越低越好)。TTFT 是首 Token 时间，即看到内容出现前需要等待的时间(越低越好)。',
        'Percent of requests that succeeded over the last 30 days. OpenRouter monitors every provider continuously and automatically retries on the next-best provider when one returns an error.': '过去 30 天请求成功的百分比。OpenRouter 持续监控每个提供商，当某个提供商返回错误时，会自动在下一个最佳提供商上重试。',
        'When an error occurs in an upstream provider, we can recover by routing to another healthy provider, if your request filters allow it. You can access uptime data programmatically through the': '当上游提供商出错时，如果您的请求过滤条件允许，我们可以通过路由到其他健康的提供商来恢复。您可以通过以下 API 以编程方式访问可用性数据:',
        'Scores on standardized evaluations. Higher percentages are better — and rank percentile shows where this model lands among all models on OpenRouter.': '标准化评测的得分。百分比越高越好，排名百分位显示该模型在 OpenRouter 所有模型中的位置。',
        'Different companies host the same model. OpenRouter routes your request to one of them based on the routing mode you pick — Balanced (price + speed), Nitro (fastest), or Exacto (highest tool-calling accuracy).': '不同的公司托管同一个模型。OpenRouter 会根据您选择的路由模式，将请求路由到其中一个——Balanced(价格 + 速度)、Nitro(最快)或 Exacto(工具调用准确率最高)。',
        'about our load balancing and customization options.': '了解我们的负载均衡和自定义选项。',

        // 基准测试版块
        'Intelligence Index': '智能指数',
        'Better than 54% of models compared': '优于所比较模型中 54% 的模型',
        'Better than 62% of models compared': '优于所比较模型中 62% 的模型',
        'Better than 56% of models compared': '优于所比较模型中 56% 的模型',
        'Coding Index': '编码指数',
        'Agentic Index': '智能体指数',
        'Graduate-level scientific reasoning': '研究生级别的科学推理',
        'Humanity\u2019s Last Exam': '人类最后的考试',
        'Humanity\'s Last Exam': '人类最后的考试',
        'Instruction-following benchmark': '指令遵循基准测试',
        'Conversational AI agents in dual-control scenarios': '双控场景下的对话式 AI 智能体',
        'Long context reasoning evaluation': '长上下文推理评测',
        'Economically valuable tasks': '具有经济价值的任务',
        'Research-level physics reasoning': '研究级别的物理推理',
        'Coding': '编码',
        'Python programming for scientific computing': '用于科学计算的 Python 编程',
        'Agentic coding & terminal use': '智能体编码与终端使用',
        'Knowledge': '知识',
        'Proportion of correctly answered questions': '正确回答问题的比例',
        'Rate of avoiding hallucination among non-correct responses': '非正确回复中避免幻觉的比例',
        'Metrics sourced from': '指标数据来源',

        // 使用该模型的应用
        'Public apps that send the most traffic to this model. Good signal for what real production workloads look like — and a hint at which use cases this model is best suited for.': '为这个模型带来最多流量的公开应用。这能反映真实的生产负载情况，也暗示了这个模型最适合哪些使用场景。',
        'Token volume and request traffic to this model over time.': '该模型随时间变化的 Token 用量和请求流量。',
        'Prompt tokens measure input size. Reasoning tokens show internal thinking before a response. Completion tokens reflect total output length.': '提示词 Token 衡量输入大小。推理 Token 显示响应前的内部思考。补全 Token 反映总输出长度。',

        // 快速开始
        'Drop-in code to call this model. OpenRouter\u2019s API is OpenAI-compatible — most SDKs work by just swapping the base URL. The only thing that changes between models is the model slug below.': '直接复制代码即可调用此模型。OpenRouter 的 API 兼容 OpenAI——大多数 SDK 只需替换基础 URL 即可使用。不同模型之间唯一变化的是下面的模型标识。',
        'Drop-in code to call this model. OpenRouter\'s API is OpenAI-compatible — most SDKs work by just swapping the base URL. The only thing that changes between models is the model slug below.': '直接复制代码即可调用此模型。OpenRouter 的 API 兼容 OpenAI——大多数 SDK 只需替换基础 URL 即可使用。不同模型之间唯一变化的是下面的模型标识。',
        'Create an API key from your OpenRouter dashboard and set it as an environment variable:': '从您的 OpenRouter 控制台创建 API 密钥，并将其设置为环境变量:',
        'Make your first request': '发起您的第一个请求',
        'Use': '使用',
        'with the OpenRouter API:': '与 OpenRouter API 一起使用:',
        'OpenRouter provides an OpenAI-compatible completion API to 400+ models & providers that you can call directly, or using the OpenAI SDK. Additionally, some third-party SDKs are available.': 'OpenRouter 提供兼容 OpenAI 的补全 API，支持 400+ 模型和提供商，您可以直接调用，或使用 OpenAI SDK。此外还提供一些第三方 SDK。',
        'In the examples below, the': '下面的示例中，',
        'OpenRouter-specific headers': 'OpenRouter 专属请求头',
        'are optional. Setting them allows your app to appear on the OpenRouter leaderboards.': '为可选项。设置它们可以让您的应用出现在 OpenRouter 排行榜上。',
        'Using third-party SDKs': '使用第三方 SDK',
        'For information about using third-party SDKs and frameworks with OpenRouter, please see our': '有关使用第三方 SDK 和框架与 OpenRouter 集成的信息，请参阅我们的',
        'frameworks documentation': '框架文档',
        'Enable streaming': '启用流式传输',
        'to your request body to receive responses as server-sent events:': '添加到请求体中以接收服务器推送事件形式的响应:',
        'Sends a request for a model response for the given chat conversation. Supports both streaming and non-streaming modes.': '为给定的聊天对话发送模型响应请求。支持流式和非流式模式。',
        'optional — your site URL, for rankings': '可选 — 您的站点 URL，用于排行榜',
        'optional — your site name, for rankings': '可选 — 您的站点名称，用于排行榜',
        'Creates a streaming or non-streaming response using the OpenAI Responses API format.': '使用 OpenAI Responses API 格式创建流式或非流式响应。',
        'Creates a message using the Anthropic Messages API format. Supports text, images, PDFs, tools, and extended thinking.': '使用 Anthropic Messages API 格式创建消息。支持文本、图像、PDF、工具和扩展思考。',
        'This sets the upper limit for the number of tokens the model can generate in response.': '设置模型在响应中可以生成的最大 Token 数上限。',
        'This setting influences the variety in the model\u2019s responses.': '此设置影响模型响应的多样性。',
        'This setting influences the variety in the model\'s responses.': '此设置影响模型响应的多样性。',
        'This setting limits the model\u2019s choices to a percentage of likely tokens: only the top tokens whose probabilities add up to P.': '此设置将模型的选择限制在一定百分比的候选 Token 中:仅选择概率之和达到 P 的顶部 Token。',
        'This setting limits the model\'s choices to a percentage of likely tokens: only the top tokens whose probabilities add up to P.': '此设置将模型的选择限制在一定百分比的候选 Token 中:仅选择概率之和达到 P 的顶部 Token。',
        'This limits the model\u2019s choice of tokens at each step, making it choose from a smaller set.': '这会限制模型每一步对 Token 的选择，使其从更小的集合中挑选。',
        'This limits the model\'s choice of tokens at each step, making it choose from a smaller set.': '这会限制模型每一步对 Token 的选择，使其从更小的集合中挑选。',
        'Stop generation immediately if the model encounter any token specified in the stop array.': '如果模型遇到停止数组中的任何 Token，立即停止生成。',
        'Tool calling parameter, following OpenAI\u2019s tool calling request shape.': '工具调用参数，遵循 OpenAI 的工具调用请求格式。',
        'Tool calling parameter, following OpenAI\'s tool calling request shape.': '工具调用参数，遵循 OpenAI 的工具调用请求格式。',
        'Controls which (if any) tool is called by the model.': '控制模型调用哪个工具(如果有)。',
        'Forces the model to produce specific output format.': '强制模型生成特定的输出格式。',

        // 延迟/吞吐量
        'Cache Hit Rate by Provider': '各提供商的缓存命中率',
        'Tool Call Error Rate by Provider': '各提供商的工具调用错误率',
        'Structured Output Error Rate by Provider': '各提供商的结构化输出错误率',
        'Rolling average over the past 32 days — the same lookback window used for quality-based routing': '过去 32 天的滚动平均值——与基于质量的路由使用的回溯窗口相同',
        'Median End-to-End Latency on OpenRouter': 'OpenRouter 上的中位端到端延迟',
        'Median Latency on OpenRouter': 'OpenRouter 上的中位延迟',
        'Median Throughput on OpenRouter': 'OpenRouter 上的中位吞吐量',
        'Latency / throughput percentile': '延迟 / 吞吐量百分位数',

        // 模型竞技场
        'Models Arena': '模型竞技场',
        'Agents Arena': '智能体竞技场',
        'Rank': '排名',
        'Asciiart': 'ASCII 艺术',
        'Code Categories': '代码分类',
        'Data Visualization': '数据可视化',
        'Game Development': '游戏开发',
        'UI Component': 'UI 组件',
        'Website': '网站',
        'Full Stack': '全栈',
        'Mobile Apps': '移动应用',
        'Webapps': 'Web 应用',

        // 相关模型
        'Fast-mode variant of': '的快速模式变体',
        '- identical capabilities with higher output speed at 2x pricing relative to regular Opus 5.': '— 与常规 Opus 5 能力相同，输出速度更快，价格为 2 倍。',
        '- identical capabilities with higher output speed at 2x pricing relative to regular Opus 4.8.': '— 与常规 Opus 4.8 能力相同，输出速度更快，价格为 2 倍。',
        '- identical capabilities with higher output speed at premium 6x pricing.': '— 能力相同，输出速度更快，价格为 6 倍。',
        'This model always redirects to the latest model in the Claude Fable family.': '此模型始终重定向到 Claude Fable 系列中的最新模型。',
        'This model always redirects to the latest model in the Anthropic Claude Haiku family.': '此模型始终重定向到 Anthropic Claude Haiku 系列中的最新模型。',
        'This model always redirects to the latest model in the Anthropic Claude Sonnet family.': '此模型始终重定向到 Anthropic Claude Sonnet 系列中的最新模型。',
        'This model always redirects to the latest model in the Claude Opus family.': '此模型始终重定向到 Claude Opus 系列中的最新模型。',
        'This model always redirects to the latest model in the DeepSeek V4 Flash family.': '此模型始终重定向到 DeepSeek V4 Flash 系列中的最新模型。',
        'For users upgrading from earlier Opus versions, see our': '从早期 Opus 版本升级的用户，请参阅我们的',
        'official migration guide here': '官方迁移指南',
        'Read more at the': '更多信息请阅读',
        'blog post here': '博客文章',
        'See the launch announcement and benchmark results': '查看发布公告和基准测试结果',
        'here': '此处',
        'Learn more in Anthropic\u2019s docs:': '更多信息请参阅 Anthropic 的文档:',
        'Learn more in Anthropic\'s docs:': '更多信息请参阅 Anthropic 的文档:',
        'This model is currently pointing to': '此模型当前指向',
        'It does not support image inputs.': '它不支持图像输入。',
        'New Claude 3.5 Sonnet delivers better-than-Opus capabilities, faster-than-Sonnet speeds, at the same Sonnet prices. Sonnet is particularly good at:': '全新的 Claude 3.5 Sonnet 提供超越 Opus 的能力、快于 Sonnet 的速度，以及和 Sonnet 相同的价格。Sonnet 尤其擅长:',
        'Responses are AI-generated. Verify before relying on them.': '回复由 AI 生成。使用前请核实。',
        'Drop-in code to call this model with OpenRouter\u2019s OpenAI-compatible API.': '使用 OpenRouter 兼容 OpenAI 的 API 直接调用此模型的示例代码。',
        'Drop-in code to call this model with OpenRouter\'s OpenAI-compatible API.': '使用 OpenRouter 兼容 OpenAI 的 API 直接调用此模型的示例代码。',
      },
      regexp: [
        // 吞吐量/延迟统计说明
        [/^P50, best across providers$/, 'P50，各提供商最佳'],
        [/^P50, best provider$/, 'P50，最佳提供商'],
        [/^All locations$/, '所有地区'],
        // 价格历史标题,如 "Claude Sonnet 4.5 — Price History"
        [/^(.+) \u2014 Price History$/, '$1 — 价格历史'],
      ],
      title: {
        static: {},
        regexp: [
          // "模型名 - API Pricing & Benchmarks | OpenRouter"
          [/^(.+) - API Pricing & Benchmarks \| OpenRouter$/, '$1 - API 定价与基准测试 | OpenRouter'],
        ],
      },
    },

    /* ------------------------------ 融合页 ------------------------------ */
    fusion: {
      static: {
        'Model Fusion': '模型融合',
        'New fusion': '新建融合',
        'No runs yet.': '还没有运行记录。',
        'Run multiple models side-by-side, run an analysis, and fuse into the best result.': '并排运行多个模型，进行分析，并融合出最佳结果。',
        'Synthesizer': '合成器',
        'Improve your prompt': '优化您的提示词',
        'Analyzing your prompt...': '正在分析您的提示词...',
        'Add Model': '添加模型',
        'Claude Opus Latest': 'Claude Opus 最新版',
        'OpenAI GPT Latest': 'OpenAI GPT 最新版',
        'Google Gemini Pro Latest': 'Google Gemini Pro 最新版',
        'Responses are AI-generated and can be inaccurate. Review all outputs before relying on them.': '回复由 AI 生成，可能不准确。在依赖之前请审查所有输出。',
      },
      regexp: [],
      title: {
        static: {
          'Model Fusion | OpenRouter': '模型融合 | OpenRouter',
        },
        regexp: [],
      },
    },

    /* ------------------------------ 聊天页 ------------------------------ */
    chat: {
      static: {
        'Add Model': '添加模型',
        'Add Model (⌘J)': '添加模型 (⌘J)',
        'Flagship models': '旗舰模型',
        'Best roleplay models': '最佳角色扮演模型',
        'Best coding models': '最佳编程模型',
        'Reasoning models': '推理模型',
        'Multimodal models': '多模态模型',
        'All models': '所有模型',
        'Select': '选择',
        'Chats': '聊天记录',
        'Back to Home': '返回首页',
        'Back to chats': '返回聊天列表',
        'Open chats': '打开聊天',
        '0 rooms': '0 个房间',
        'No matching rooms': '没有匹配的房间',
        'Search rooms...': '搜索房间...',
        'Server tools': '服务端工具',
        'Server tools documentation': '服务端工具文档',
        'Close server tools': '关闭服务端工具',
        'Web Search': '联网搜索',
        'Search the web for current information': '搜索网络获取最新信息',
        'Auto · Medium': '自动 · 中',
        'Web Fetch': '网页抓取',
        'Retrieve content from URLs': '从 URL 获取内容',
        'Auto': '自动',
        'Image Generation': '图像生成',
        'Generate images from text': '根据文本生成图像',
        'Datetime': '日期时间',
        'Current date and time info': '当前日期和时间信息',
        'Multi-model consensus and analysis': '多模型共识与分析',
        '3 models': '3 个模型',
        'Advisor': '顾问',
        'Consult a stronger model for guidance': '咨询更强的模型获取指导',
        'Subagent': '子智能体',
        'Delegate tasks to smaller, faster models': '将任务委派给更小、更快的模型',
        'Send message': '发送消息',
        'Start recording': '开始录音',
        'Add to message': '添加到消息',
        'View mode': '视图模式',
        'Room settings': '房间设置',
        'Zero Data Retention settings': '零数据保留设置',
        'Toggle Web Search': '切换联网搜索',
        'Toggle Web Fetch': '切换网页抓取',
        'Toggle Image Generation': '切换图像生成',
        'Toggle Datetime': '切换日期时间',
        'Toggle Fusion': '切换融合',
        'Toggle Advisor': '切换顾问',
        'Toggle Subagent': '切换子智能体',
        'Select an Audio Input Model': '选择音频输入模型',
        'Select a Video Input Model': '选择视频输入模型',
        'Search models': '搜索模型',
        'Ask anything': '输入任何问题',
        'Ask anything\u2026': '输入任何问题…',
        'Ask anything...': '输入任何问题…',
        'What can I help with?': '有什么可以帮您?',
        'How can I help you today?': '今天有什么可以帮您?',
        'Responses are AI-generated and can be inaccurate. Review all outputs before relying on them.': '回复由 AI 生成，可能不准确。在依赖之前请审查所有输出。',
        'Responses are generated using AI and may contain mistakes.': '回复由 AI 生成，可能包含错误。',
        'Import Character': '导入角色',
        'Click to upload': '点击上传',
        'drag and drop': '拖放',
        'your character card': '您的角色卡',
        'JSON, WebP or PNG (both v1 and v2 are supported)': 'JSON、WebP 或 PNG(支持 v1 和 v2)',
        'Conversation settings': '对话设置',
        'Model settings': '模型设置',
        'Parameters': '参数',
        'Clear chat': '清空聊天',
        'Chat deleted': '聊天已删除',
        'Delete message': '删除消息',
        'Copy message': '复制消息',
        'Edit message': '编辑消息',
        'Message': '消息',
        'Untitled chat': '未命名聊天',
        'Stop generating': '停止生成',
        'Stream': '流式输出',
        'Sending': '发送中',
        'Room': '房间',
        'rooms': '房间',
      },
      regexp: [],
      title: {
        static: {
          'AI Chat Playground - Compare AI Models Side by Side | OpenRouter': 'AI 聊天试玩台 - 并排对比 AI 模型 | OpenRouter',
        },
        regexp: [],
      },
    },

    /* ------------------------------ 排行榜 ------------------------------ */
    rankings: {
      static: {
        'Top Models': '热门模型',
        'Leaderboard': '排行榜',
        'Top models by task': '按任务排名的热门模型',
        'Cost per session': '每次会话成本',
        'Market Share': '市场份额',
        'Fastest models': '最快模型',
        'Languages': '语言',
        'Programming': '编程',
        'Context Length': '上下文长度',
        'Images': '图像',
        'Top Apps': '热门应用',
        'AI Model Rankings': 'AI 模型排行榜',
        'Live LLM rankings based on benchmarks and real data from millions of people using models through OpenRouter.': '基于基准测试和数百万用户通过 OpenRouter 使用模型的真实数据，实时更新的 LLM 排名。',
        'text': '文本',
        'image': '图像',
        'embeddings': '向量嵌入',
        'audio': '音频',
        'video': '视频',
        'rerank': '重排序',
        'speech': '语音',
        'transcription': '转录',
        'Weekly usage of models across OpenRouter': 'OpenRouter 上各模型的每周用量',
        'Linear': '线性',
        'Log': '对数',
        'LLM Leaderboard': 'LLM 排行榜',
        'Compare the most popular models on OpenRouter': '对比 OpenRouter 上最受欢迎的模型',
        'This Week': '本周',
        'This Month': '本月',
        'All Time': '全部时间',
        'Show more': '显示更多',
        'Each task\u2019s leading models, ranked by share of spend on OpenRouter': '各任务的领先模型，按在 OpenRouter 上的花费占比排名',
        'spend': '花费',
        'Share of spend': '花费占比',
        'What one coding-agent session typically costs (paid usage), by session length': '按会话时长统计，一次编码智能体会话的典型费用(付费使用)',
        'Absolute': '绝对',
        'Percentage': '百分比',
        'Rankings sections': '排行榜版块',
        'Rankings page sections': '排行榜页面版块',
        'Y-axis scale': 'Y 轴刻度',
        'Shown are the sum of prompt and completion tokens per model, including reasoning tokens. Open models are those with publicly available weights.': '显示的是每个模型的提示词与补全 Token 总和，包括推理 Token。开放模型指权重公开的模型。',
        'Filter models by openness': '按开放程度筛选模型',
        'Filter by time window': '按时间窗口筛选',
        'Information': '信息',
        'Loading task rankings': '加载任务排名中',
        'Median spend per session over the last 30 days, on a log scale. A session is attributed to a model when that model served at least 80% of its tokens.': '过去 30 天每次会话的中位花费(对数刻度)。当某个模型服务了至少 80% 的 Token 时，该会话归因于该模型。',
        'Loading cost per session rankings': '加载每次会话成本排名中',
        'Chart value display': '图表数值显示',
        'Loading rankings chart and rows': '加载排名图表和行中',
        'Loading benchmark rankings': '加载基准测试排名中',
        'Loading performance rankings': '加载性能排名中',
        'Loading app rankings': '加载应用排名中',
        'by': '来自',
        'Tokens': 'Token 数',
        'Median cost': '中位费用',
        'New entry': '新上榜',
        'Position': '名次',
        'Change': '变化',
        'Rank': '排名',
        'Total votes': '总票数',
        'Weekly votes': '周票数',

        // 排名分类版块
        'View all text models': '查看全部文本模型',
        'Compare text request share by model author on OpenRouter.': '按模型作者比较 OpenRouter 上的文本请求份额。',
        'Compare models by natural language on OpenRouter': '按自然语言比较 OpenRouter 上的模型',
        'English': '英语',
        'Compare models by programming language on OpenRouter': '按编程语言比较 OpenRouter 上的模型',
        'Requests by prompt & completion length on OpenRouter': '按提示词与补全长度统计的请求量',
        'Tool usage across models on OpenRouter': '各模型上的工具使用情况',
        'Total images processed on OpenRouter': 'OpenRouter 处理的图像总数',
        '1K - 10K tokens': '1K - 10K Token',
        '1K - 100K tokens': '1K - 100K Token',
      },
      regexp: [],
      title: {
        static: {
          'LLM Rankings | OpenRouter': 'LLM 排行榜 | OpenRouter',
        },
        regexp: [],
      },
    },

    /* ------------------------------ 应用页 ------------------------------ */
    apps: {
      static: {
        'Explore': '探索',
        'Top Apps': '热门应用',
        'Featured Agents': '精选智能体',
        'Agent': '智能体',
        'Agents': '智能体',
        'Tools': '工具',
        'Categories': '类别',
        'Category': '类别',
        'Launch': '启动',
        'Visit': '访问',
        'Source code': '源代码',
        'Verified': '已验证',
        'Created by': '创建者',
        'Users': '用户',
        'Monthly users': '月度用户',
        'Weekly users': '周用户',
        'Total users': '总用户',
        'Popularity': '热度',
        'Submitted': '已提交',
        'Report': '举报',
        'Submit app': '提交应用',
        'App URL': '应用 URL',
        'App name': '应用名称',
        'App description': '应用描述',
        'We\u2019ll review your submission': '我们将审核您的提交',

        // 应用排行榜版块
        'App & Agent Rankings': '应用与智能体排行榜',        'Most Popular': '最受欢迎',
        'Largest public apps and agents': '最大的公开应用和智能体',
        'opting into': '选择加入',
        'usage tracking on OpenRouter.': 'OpenRouter 上的使用跟踪。',
        'Fastest growing this week': '本周增长最快',
        'Top Coding Agents': '热门编码智能体',
        'Top Productivity': '热门效率工具',
        'Top Creative': '热门创意工具',
        'Top Entertainment': '热门娱乐应用',
        'Global Ranking': '全球排名',
        'Personal Agents': '个人智能体',
        'CLI Agents': 'CLI 智能体',
        'IDE Extensions': 'IDE 扩展',
        'General Chat': '通用聊天',
        'Game': '游戏',
        'Roleplay': '角色扮演',
        'Creative Writing': '创意写作',
        'Programming App': '编程应用',
        'Token volume': 'Token 总量',
      },
      regexp: [],
      title: {
        static: {
          'App & Agent Rankings | OpenRouter': '应用与智能体排行榜 | OpenRouter',
        },
        regexp: [],
      },
    },

    /* ------------------------------ 文档页 ------------------------------ */
    docs: {
      static: {
        'Documentation Index': '文档索引',
        'Fetch the complete documentation index at:': '在此处获取完整文档索引:',
        'Use this file to discover all available pages before exploring further.': '在深入探索之前，使用此文件发现所有可用页面。',
        'Navigation': '导航',
        'Overview': '概览',
        'Quickstart': '快速开始',
        'Client SDKs': '客户端 SDK',
        'Agent SDK': '智能体 SDK',
        'Cookbook': '示例集',
        'Batch': '批量处理',
        'Principles': '原则',
        'Multimodal': '多模态',
        'Authentication': '身份认证',
        'Stripe Projects': 'Stripe 项目',
        'Report Feedback': '反馈问题',
        'Models & Routing': '模型与路由',
        'Model Fallbacks': '模型回退',
        'Provider Selection': '提供商选择',
        'Private Models': '私有模型',
        'Model Variants': '模型变体',
        'Routers': '路由器',
        'Workspaces': '工作区',
        'Workspace Budgets': '工作区预算',
        'Switching Workspaces': '切换工作区',
        'Single Sign-On (SSO)': '单点登录 (SSO)',
        'SCIM Group Mappings': 'SCIM 组映射',
        'Presets': '预设',
        'Custom Classifiers': '自定义分类器',
        'Response Caching': '响应缓存',
        'Server Tools': '服务端工具',
        'Plugins': '插件',
        'Message Transforms': '消息转换',
        'Zero Completion Insurance': '零补全保障',
        'App Attribution': '应用归因',
        'Guardrails': '护栏',
        'Service Tiers': '服务层级',
        'Sovereign AI': '主权 AI',
        'Router Metadata': '路由元数据',
        'Input & Output Logging': '输入与输出日志',
        'Broadcast': '广播',
        'Where Ori writes files': 'Ori 写入文件的位置',
        'Data Collection': '数据收集',
        'Provider Logging': '提供商日志',
        'Best Practices': '最佳实践',
        'Latency and Performance': '延迟与性能',
        'Prompt Caching': '提示词缓存',
        'Uptime Optimization': '可用性优化',
        'Reasoning Tokens': '推理 Token',
        'Community': '社区',
        'For Providers': '面向提供商',
        'Frameworks and Integrations Overview': '框架与集成概览',
        'On this page': '本页目录',
        'Copy page': '复制页面',
        'Get started with OpenRouter': 'OpenRouter 快速入门',
        'OpenRouter gives you access to hundreds of AI models through a single API endpoint. It handles fallbacks automatically and picks the most cost-effective option for each request.': '通过一个 API 端点，OpenRouter 让您可以访问数百个 AI 模型。它会自动处理回退，并为每个请求选择最具性价比的选项。',
        'There are three ways to integrate with OpenRouter, depending on how much control you want:': '根据您想要的掌控程度，有三种方式集成 OpenRouter:',
        'Approach': '方式',
        'Best for': '适用场景',
        'Full control, any language, no dependencies': '完全掌控，支持任何语言，无依赖',
        'Type-safe model calls with minimal overhead': '类型安全的模型调用，开销最小',
        'Building agents with tool use, loops, and state': '构建带工具调用、循环和状态的智能体',
        'The most direct way to use OpenRouter. Send standard HTTP requests to the': '使用 OpenRouter 最直接的方式。向以下端点发送标准 HTTP 请求:',
        'endpoint. It works with any language or framework.': '端点。它适用于任何语言或框架。',
        'Request Builder': '请求构建器',
        'to generate OpenRouter API requests in the language of your choice.': '以您选择的语言生成 OpenRouter API 请求。',
        'The examples below use': '下面的示例使用',
        'latest alias': '最新别名',
        'that always resolves to the newest OpenAI flagship model, so your code keeps using the freshest version without redeploying. You can substitute any model slug here. Browse the full catalog at': '它始终解析为最新的 OpenAI 旗舰模型，让您的代码无需重新部署即可持续使用最新版本。您可以在此替换任何模型标识。在以下网址浏览完整目录:',
        'or list every available slug programmatically via the': '或通过以下端点以编程方式列出所有可用模型标识:',
        'The API also supports': 'API 还支持',
        'streaming': '流式传输',
        'You can also use the': '您还可以使用',
        'pointed at OpenRouter as a drop-in replacement.': '指向 OpenRouter，作为即插即用的替代品。',
        'wrap the OpenRouter API with full type safety, auto-generated types from the OpenAPI spec, and zero boilerplate. It\u2019s intentionally lean, a thin layer over the REST API.': '以完全类型安全的方式封装 OpenRouter API，自动从 OpenAPI 规范生成类型，零样板代码。它刻意保持精简，是 REST API 之上的薄层。',
        'First, install the SDK:': '首先，安装 SDK:',
        'install': '安装',
        'add': '添加',
        'Then use it in your code:': '然后在代码中使用:',
        'See the full': '查看完整的',
        'Client SDKs documentation': '客户端 SDK 文档',
        'for streaming, embeddings, and the complete API reference.': '了解流式传输、向量嵌入和完整的 API 参考。',
        'provides higher-level primitives for building AI agents. It handles multi-turn conversation loops, tool execution, and state management automatically via the': '为构建 AI 智能体提供更高级的原语。它通过以下方式自动处理多轮对话循环、工具执行和状态管理:',
        'function.': '函数。',
        'Install the package:': '安装软件包:',
        'Build an agent with tools:': '使用工具构建智能体:',
        'The SDK sends the prompt, receives a tool call from the model, executes': 'SDK 发送提示词，接收模型的工具调用，执行',
        'feeds the result back, and returns the final response, all in one': '将结果回传，并在一次调用中返回最终响应。',
        'Agent SDK documentation': '智能体 SDK 文档',
        'for stop conditions, streaming, dynamic parameters, and more.': '了解停止条件、流式传输、动态参数等。',
        'You can also use the OpenAI SDK pointed at OpenRouter as a drop-in replacement. This is useful if you have existing code built on the OpenAI SDK and want to access OpenRouter\u2019s model catalog without changing your code structure.': '您也可以将 OpenAI SDK 指向 OpenRouter，作为即插即用的替代品。如果您已有基于 OpenAI SDK 的代码，并且不想更改代码结构就能访问 OpenRouter 的模型目录，这将非常有用。',
        'For information about using third-party SDKs and frameworks with OpenRouter, please': '有关将第三方 SDK 和框架与 OpenRouter 一起使用的信息，请',
        'see our frameworks documentation.': '参阅我们的框架文档。',
        'If you write code with an AI coding tool (Claude Code, Cursor, Codex, and others), connect the': '如果您使用 AI 编程工具(Claude Code、Cursor、Codex 等)编写代码，请连接',
        'OpenRouter MCP server': 'OpenRouter MCP 服务器',
        'It\u2019s a remote server hosted by OpenRouter, so there\u2019s nothing to install. Your assistant can pull live OpenRouter data (which models exist, what they cost, your credit balance, usage rankings) and search these docs while you build. That way its suggestions reflect current data instead of stale training knowledge. Add one URL to your MCP client and approve an OAuth login:': '它是由 OpenRouter 托管的远程服务器，无需安装任何东西。您的助手可以实时获取 OpenRouter 数据(有哪些模型、价格、您的余额、使用排名)，并在您开发时搜索这些文档。这样它的建议反映的是最新数据，而不是过时的训练知识。向您的 MCP 客户端添加一个 URL 并批准 OAuth 登录:',
        'See the': '参阅',
        'MCP server guide': 'MCP 服务器指南',
        'for per-client setup and the full tool list. To run models in your app, keep calling the OpenRouter API directly.': '了解各客户端的配置方法和完整工具列表。要在应用中运行模型，请继续直接调用 OpenRouter API。',
        'Looking for information about free models and rate limits? Please see the': '想了解免费模型和速率限制?请参阅',
        'Ask Assistant': '咨询助手',
        'Was this page helpful?': '此页对您有帮助吗?',
        'Edit this page': '编辑此页',
        'Table of contents': '目录',
        'Search documentation': '搜索文档',
        'Ctrl K': 'Ctrl K',
        'Ctrl+I': 'Ctrl+I',
      },
      regexp: [],
      title: {
        static: {
          'OpenRouter Quickstart Guide': 'OpenRouter 快速入门指南',
          'OpenRouter Docs': 'OpenRouter 文档',
        },
        regexp: [],
      },
    },

    /* ------------------------------ 设置页 ------------------------------ */
    settings: {
      static: {
        'Create new key': '创建新密钥',
        'Key name': '密钥名称',
        'Key ID': '密钥 ID',
        'Secret': '密钥',
        'Credit limit': '额度上限',
        'Never': '永不过期',
        'Reveal': '显示',
        'Hide': '隐藏',
        'Revoke': '撤销',
        'Top up': '充值',
        'Rate limits': '速率限制',
        'RPM': 'RPM',
        'TPM': 'TPM',
        'Roles': '角色',
        'Admin': '管理员',
        'Member': '成员',
        'Owner': '所有者',
        'Invite': '邀请',
        'Invite member': '邀请成员',
        'Pending': '待处理',
        'Leave': '离开',
        'Transfer ownership': '转让所有权',
        'Requests': '请求数',
        'Errors': '错误数',
        'Cost': '费用',
        'Prompt tokens': '提示词 Token',
        'Completion tokens': '补全 Token',
        'Cache tokens': '缓存 Token',
        'Total tokens': 'Token 总计',
        'Method': '方法',
        'Transactions': '交易记录',
        'Payment method': '支付方式',
        'Card': '银行卡',
        'Crypto': '加密货币',
        'Payments': '支付',
        'Invoice': '发票',
        'Tax ID': '税号',
        'VAT': '增值税',
        'Auto-recharge': '自动充值',
        'Email notifications': '邮件通知',
        'Usage alerts': '用量提醒',
        'Spend limits': '消费上限',
        'Budget': '预算',
        'Month-to-date': '本月至今',
        'Remaining credits': '剩余额度',
        'Credit balance': '额度余额',
        'Estimated cost': '预估费用',
        'Total spend': '总花费',
        'Two-factor authentication': '两步验证',
        'API keys': 'API 密钥',
        'No keys yet': '暂无密钥',
        'Create your first key': '创建您的第一个密钥',
        'Provider permissions': '提供商权限',
        'Allow': '允许',
        'Deny': '拒绝',
        'Select all': '全选',
        'Unselect all': '取消全选',
        'Save settings': '保存设置',
        'Settings saved': '设置已保存',
        'Organization settings': '组织设置',
        'Personal': '个人',
        'Switch to': '切换到',

        // 个人资料页
        'Usage summary': '用量摘要',
        'Last 7 Days': '最近 7 天',
        'View full activity': '查看完整活动记录',
        'Daily · by model': '每日 · 按模型',
        'this month': '本月',
        'Top models': '热门模型',
        'by spend': '按花费',
        'Longest streak': '最长连续天数',
        'day': '天',
        'Avg / day': '日均',
        'Avg / week': '周均',
        'Change profile picture': '更换头像',
        'PNG, JPEG, GIF, or WebP up to 5 MB.': '支持 PNG、JPEG、GIF 或 WebP，最大 5 MB。',
        'Choose image': '选择图片',
        'Ranked by spend over the selected window': '按所选时间窗口内的花费排名',

        // 管理密钥页
        'Control your management API keys for administrative actions': '控制用于管理操作的管理 API 密钥',
        'Create a Management Key': '创建管理密钥',
        'Edit Management Key': '编辑管理密钥',
        'Disable Key': '停用密钥',
        'Are you sure you want to disable this key? You can re-enable it later.': '确定要停用此密钥吗?您可以稍后重新启用。',
        'Disable': '停用',
        'Delete Key': '删除密钥',
        'Are you sure you want to delete this key? This action cannot be undone.': '确定要删除此密钥吗?此操作无法撤销。',

        // 隐私设置页
        'Restrictions to apply globally across the account. You can further restrict API keys with guardrails inside a workspace.': '应用于整个账户的全局限制。您还可以在工作区内使用护栏进一步限制 API 密钥。',
        'Data Policies': '数据策略',
        'Set data privacy and usage restrictions.': '设置数据隐私和使用限制。',
        'Zero Data Retention': '零数据保留',
        'Only route to provider endpoints that don\u2019t store your data. Reject requests that would require data retention. Only applies to provider routing, does not apply to plugins and tools you choose to enable.': '仅路由到不存储您数据的提供商端点。拒绝需要数据保留的请求。仅适用于提供商路由，不适用于您选择启用的插件和工具。',
        'Non-frontier': '非前沿',
        'All non-frontier model requests will require ZDR endpoints.': '所有非前沿模型请求都需要 ZDR 端点。',
        'First-party Anthropic endpoints will be disabled. Bedrock and Vertex will still be enabled.': 'Anthropic 第一方端点将被停用。Bedrock 和 Vertex 仍然可用。',
        'First-party OpenAI endpoints will be disabled. Azure will still be enabled.': 'OpenAI 第一方端点将被停用。Azure 仍然可用。',
        'AI Studio endpoints will be disabled. Vertex will still be enabled.': 'AI Studio 端点将被停用。Vertex 仍然可用。',
        'SpaceXAI endpoints that retain data will be disabled.': '保留数据的 SpaceXAI 端点将被停用。',
        'Data Training': '数据训练',
        'These settings are separate from Zero Data Retention. Each endpoint toggle controls routing to endpoints with a specific data policy: enabling allows requests to be routed to those endpoints, disabling excludes them from routing.': '这些设置与零数据保留相互独立。每个端点开关控制到特定数据策略端点的路由:启用允许请求路由到这些端点，停用则将其排除在路由之外。',
        'Allow paid endpoints that train on request data': '允许在请求数据上训练的付费端点',
        'Enable providers that may anonymously use data for training purposes.': '启用可能匿名使用数据用于训练目的的提供商。',
        'Allow free endpoints that train on request data': '允许在请求数据上训练的免费端点',
        'Enable providers serving free models that may retain and/or train on prompts and completions.': '启用可能保留和/或在提示词和补全上训练的免费模型提供商。',
        'Allow free endpoints that publish prompts': '允许发布提示词的免费端点',
        'Enable providers serving free models that may publish prompts and completions to public datasets.': '启用可能将提示词和补全发布到公共数据集的免费模型提供商。',
        'Allow 1% data discount in workspaces': '允许工作区中的 1% 数据折扣',
        'Allow workspaces to consent to OpenRouter using your inputs/outputs to improve the product. Each workspace consents separately.': '允许工作区同意 OpenRouter 使用您的输入/输出来改进产品。每个工作区单独同意。',
        'Control which providers are used for routing. Leave empty to allow all.': '控制用于路由的提供商。留空则允许全部。',
        'Allowed Providers': '允许的提供商',
        'Exclusively enable these providers for your requests.': '仅对您的请求启用这些提供商。',
        'Ignored Providers': '忽略的提供商',
        'Exclude these providers from serving any requests.': '将这些提供商从所有请求中排除。',
        'Eligibility Preview': '资格预览',
        'Providers and models available based on your account settings.': '根据您的账户设置可用的提供商和模型。',
        'Prompt Injection Allowlist': '提示词注入白名单',
        'Phrases that should never trigger the prompt injection guardrail. Matching is case-insensitive and exact.': '永远不应触发提示词注入护栏的短语。匹配不区分大小写且为精确匹配。',
        'Add phrases your users legitimately send that should not trigger the prompt injection guardrail. Matching is case-insensitive and exact.': '添加您的用户合法发送且不应触发提示词注入护栏的短语。匹配不区分大小写且为精确匹配。',
        'Allowlisted phrases only take effect when the': '白名单短语仅在启用',
        'prompt injection guardrail': '提示词注入护栏',
        'is enabled for the request. Without it enabled, these patterns have no effect.': '时才生效。未启用时，这些模式不会生效。',
        'Add pattern': '添加模式',
        'Learn more': '了解更多',
        'Add': '添加',
      },
      regexp: [
        // "Keys (2)" 等带数量的标签
        [/^Keys\s*\(\s*(\d+)\s*\)$/, '密钥($1)'],
        [/^Members\s*\(\s*(\d+)\s*\)$/, '成员($1)'],
        // "509 available | 1 unavailable"
        [/^(\d+) available \| (\d+) unavailable$/, '$1 可用 | $2 不可用'],
      ],
      title: {
        static: {
          'Settings | OpenRouter': '设置 | OpenRouter',
          'API Keys | OpenRouter': 'API 密钥 | OpenRouter',
          'API Keys | Settings | OpenRouter': 'API 密钥 | 设置 | OpenRouter',
          'Credits | OpenRouter': '额度 | OpenRouter',
          'Billing | OpenRouter': '账单 | OpenRouter',
          'Usage | OpenRouter': '用量 | OpenRouter',
          'Activity | OpenRouter': '活动记录 | OpenRouter',
          'Limits | OpenRouter': '限制 | OpenRouter',
          'Providers | OpenRouter': '提供商 | OpenRouter',
          'Organization | OpenRouter': '组织 | OpenRouter',
          'Account | OpenRouter': '账户 | OpenRouter',
          'Management Keys | OpenRouter': '管理密钥 | OpenRouter',
          'Privacy Settings | OpenRouter': '隐私设置 | OpenRouter',
        },
        regexp: [],
      },
    },

    /* ------------------------------ 工作区 ------------------------------ */
    workspaces: {
      static: {
        'Manage your workspaces and their configurations.': '管理工作区及其配置。',
        'New Workspace': '新建工作区',
        'Description': '描述',
        'Actions': '操作',
        'The initial workspace for your account. Includes all API Keys, Presets, and other configurations previously created.': '您账户的初始工作区。包含之前创建的所有 API 密钥、预设和其他配置。',

        // 工作区概览
        'Introducing Workspaces!': '全新工作区功能!',
        'Organize your OpenRouter usage into different environments with separate keys, configurations, budgets, and rules.': '将您的 OpenRouter 使用组织到不同的环境中，每个环境有独立的密钥、配置、预算和规则。',
        'We created this workspace for you with all your existing API keys, routing rules, privacy settings, guardrails, and configurations.': '我们为您创建了这个工作区，包含您现有的所有 API 密钥、路由规则、隐私设置、护栏和配置。',
        'This Week\u2019s': '本周',
        'This Week\u2019s Spend': '本周花费',
        'This Week\u2019s Usage': '本周用量',
        'Requests': '请求数',
        'Create and manage API keys in this workspace.': '在此工作区创建和管理 API 密钥。',
        'Set budgets, model/provider restrictions, privacy, and content policies.': '设置预算、模型/提供商限制、隐私和内容策略。',
        'Use your own provider API keys on OpenRouter.': '在 OpenRouter 上使用您自己的提供商 API 密钥。',
        'Set routing policies for models and providers.': '为模型和提供商设置路由策略。',
        'Save shortcuts for system prompts and request parameters.': '保存系统提示词和请求参数的快捷方式。',
        'Configure plugin behavior for this workspace.': '配置此工作区的插件行为。',
        'Connect monitoring tools like Langfuse or Datadog to track usage.': '连接 Langfuse 或 Datadog 等监控工具来跟踪用量。',
        'Edit the workspace name and description.': '编辑工作区名称和描述。',

        // 工作区设置
        'General': '常规',
        'ID': 'ID',
        'Enable 1% discount on all LLMs': '启用所有 LLM 的 1% 折扣',
        'Consent to OpenRouter using your inputs/outputs to improve the product.': '同意 OpenRouter 使用您的输入/输出来改进产品。',
        'Video Generation': '视频生成',
        'Default Webhook URL': '默认 Webhook URL',
        'Receives video generation delivery events for this workspace.': '接收此工作区的视频生成交付事件。',
        'Webhook Signing Secret': 'Webhook 签名密钥',
        'Used to verify webhook payload signatures.': '用于验证 Webhook 负载签名。',
        'No signing secret configured.': '未配置签名密钥。',
        'Generate Signing Secret': '生成签名密钥',
        'This will generate a new signing secret for webhook signature verification. This change takes effect immediately.': '这将生成一个新的签名密钥用于 Webhook 签名验证。更改会立即生效。',
        'Generate Secret': '生成密钥',
        'Leave Workspace': '离开工作区',
        'Leave workspace': '离开工作区',
        'Are you sure you want to leave': '确定要离开',
        'You will lose access to this workspace and its resources.': '您将失去对此工作区及其资源的访问权限。',

        // 护栏页
        'Set spending limits, data privacy rules, and model/provider restrictions for API keys in this workspace.': '在此工作区为 API 密钥设置消费限制、数据隐私规则以及模型/提供商限制。',
        'New Guardrail': '新建护栏',
        'Policies': '策略',
        'Members': '成员',
        'Workspace Guardrail': '工作区护栏',
        'Default policy automatically applied to every key in this workspace.': '自动应用于此工作区每个密钥的默认策略。',
        'No policies': '无策略',
        'Discard new guardrail?': '放弃新护栏?',
        'Your in-progress edits won\u2019t be saved.': '您进行中的编辑将不会被保存。',
        'Keep editing': '继续编辑',
        'Discard': '放弃',

        // BYOK 页
        'Use your own provider API keys on OpenRouter': '在 OpenRouter 上使用您自己的提供商 API 密钥',
        'Available': '可用',
        'Not configured': '未配置',
        'Key Priority and Fallback': '密钥优先级与回退',
        'OpenRouter always prioritizes using your provider keys when available.': 'OpenRouter 始终优先使用您的提供商密钥。',
        'By default, if your key encounters a rate limit or failure, OpenRouter will fall back to using shared OpenRouter endpoints.': '默认情况下，如果您的密钥遇到速率限制或失败，OpenRouter 将回退到使用共享的 OpenRouter 端点。',
        'You can configure individual keys with "Always use this key" to prevent any fallback to OpenRouter endpoints. When this option is enabled, OpenRouter will only use your key for requests to that provider. This may result in rate limit errors if your key is exhausted, but ensures all requests go through your account.': '您可以为单个密钥启用"始终使用此密钥"以防止回退到 OpenRouter 端点。启用此选项后，OpenRouter 对该提供商的请求将只使用您的密钥。如果您的密钥额度耗尽，可能会导致速率限制错误，但可确保所有请求都通过您的账户。',
        'If you wish to never use shared OpenRouter endpoints for a model, you must': '如果您希望某个模型永不使用共享的 OpenRouter 端点，则必须',
        'both': '同时',
        'specify "Always use this key" and pin the provider by specifying it as': '指定"始终使用此密钥"，并将提供商固定为',
        'your only provider': '您唯一的提供商',
        'when making the request.': '在发起请求时。',
        'Always use this key': '始终使用此密钥',

        // 分类器页
        'Tag every generation with structured metadata for AI usage reporting. View aggregated charts in the Activity page. Create up to 10 classifiers per workspace.': '为每次生成打上结构化元数据标签，用于 AI 使用报告。在活动记录页面查看汇总图表。每个工作区最多可创建 10 个分类器。',
        'No classifiers configured': '尚未配置分类器',
        'A classifier runs a cheap model over every generation and tags it with structured metadata you define \u2014 department, task type, sensitivity, etc. Tags power org-wide dashboards without exposing prompt content to leadership.': '分类器会对每次生成运行一个廉价模型，并用您定义的结构化元数据(部门、任务类型、敏感度等)打标签。标签支持组织级仪表板，而不会向管理层暴露提示词内容。',
        'Create classifier': '创建分类器',

        // 可观测性页
        'Input & Output Logging': '输入与输出日志',
        'Show prompts and completions in your': '在您的日志中显示提示词和补全',
        'for debugging, evaluating responses, and optimizing prompts.': '用于调试、评估回复和优化提示词。',
        'Broadcast': '广播',
        'Automatically send traces from your requests to external observability platforms without additional instrumentation.': '无需额外埋点，自动将请求的追踪数据发送到外部可观测性平台。',
        'Add Destination': '添加目标',
        'Send Feedback': '发送反馈',
        'Let us know how we can improve!': '告诉我们如何改进!',

        // 插件页
        'Default Plugin Settings': '默认插件设置',
        'Configure default plugin behavior for your API requests.': '配置 API 请求的默认插件行为。',
        'Web Search': '联网搜索',
        'Augment LLM responses with real-time web search results': '使用实时网络搜索结果增强 LLM 回复',
        'PDF Inputs': 'PDF 输入',
        'Parse and extract content from uploaded PDF files': '解析并提取上传的 PDF 文件内容',
        'Response Healing': '回复修复',
        'Automatically fix malformed JSON responses from LLMs': '自动修复 LLM 返回的格式错误的 JSON',
        'Pareto Router': 'Pareto 路由器',
        'Set default coding quality tier for the Pareto code router': '为 Pareto 代码路由器设置默认编码质量等级',

        // 预设页
        'Presets are shortcuts for your system prompts, model and provider configurations, and request parameters.': '预设是系统提示词、模型与提供商配置以及请求参数的快捷方式。',
        'New Preset': '新建预设',
        'No presets yet': '暂无预设',
        'Create a preset to save your model + parameter configuration.': '创建预设以保存您的模型 + 参数配置。',

        // 路由页
        'Auto Router': '自动路由器',
        'Configure which models the Auto Router can route to.': '配置自动路由器可以路由到哪些模型。',
        'Route to the best model for each request using': '使用以下模型为每个请求路由到最佳模型:',
        '. Saved settings also apply to': '。保存的设置同样适用于',
        'Allowed Models': '允许的模型',
        'Model patterns to filter which models the auto-router can route between. Separate patterns with commas or newlines. Supports wildcards (e.g., "anthropic/*" matches all Anthropic models). Leave empty to route across every model the auto-router ranks for your request.': '用于过滤自动路由器可在哪些模型之间路由的模型模式。用逗号或换行分隔模式。支持通配符(例如 "anthropic/*" 匹配所有 Anthropic 模型)。留空则可在自动路由器为您的请求排名的所有模型之间路由。',
        'Cost / Quality Tradeoff': '成本 / 质量权衡',
        'Quality': '质量',
        'Cost': '成本',
        '0 = pure quality (best model regardless of cost), 10 = cheapest model wins. Intermediate values blend quality and cost signals.': '0 = 纯质量(不考虑成本的最佳模型)，10 = 最便宜的模型获胜。中间值混合质量与成本信号。',
        'Prevent overrides': '禁止覆盖',
        'Default Provider Sort': '默认提供商排序',
        'Choose how providers should be sorted for your requests.': '选择您的请求中提供商的排序方式。',
        'Choose how providers should be sorted. Individual requests can override this setting.': '选择提供商的排序方式。单个请求可以覆盖此设置。',
        'By default, OpenRouter balances low prices with high uptime.': '默认情况下，OpenRouter 在低价格与高可用性之间取得平衡。',
        'Default (balanced)': '默认(均衡)',
        'Default Model': '默认模型',
        'Set the default model for apps and fallback routing.': '为应用和回退路由设置默认模型。',
        'Apps will use this model by default, but they may override it if they choose to do so.': '应用默认使用此模型，但它们也可以选择覆盖。',
        'This model will also be used as your default': '此模型也将用作您的默认',
        'fallback model': '回退模型',
        'No default': '无默认',
      },
      regexp: [
        // "Show 57 more"
        [/^Show (\d+) more$/, '显示另外 $1 个'],
      ],
      title: {
        static: {
          'Workspaces | OpenRouter': '工作区 | OpenRouter',
          'Workspace Overview | Settings | OpenRouter': '工作区概览 | 设置 | OpenRouter',
          'Workspace Settings | OpenRouter': '工作区设置 | OpenRouter',
          'Guardrails | OpenRouter': '护栏 | OpenRouter',
          'BYOK | Settings | OpenRouter': '自带密钥 | 设置 | OpenRouter',
          'Routing | Settings | OpenRouter': '路由 | 设置 | OpenRouter',
          'Presets | Settings | OpenRouter': '预设 | 设置 | OpenRouter',
          'Plugins | Settings | OpenRouter': '插件 | 设置 | OpenRouter',
          'Observability | OpenRouter': '可观测性 | OpenRouter',
          'Classifiers | OpenRouter': '分类器 | OpenRouter',
        },
        regexp: [],
      },
    },

    /* ------------------------------ 活动记录 ------------------------------ */
    activity: {
      static: {
        'Your usage across models on OpenRouter': '您在 OpenRouter 上各模型的用量',
        'Trends': '趋势',
        'Token volume': 'Token 总量',
        'Cache hit rate': '缓存命中率',
        'Blended $/1M': '混合 $/1M',
        'Top API Keys': '热门 API 密钥',
        'Top Apps': '热门应用',
        'Usage by model': '按模型用量',
        'Usage type': '用量类型',
        'OpenRouter Spend': 'OpenRouter 花费',
        'Request volume by model': '按模型的请求量',
        'Token breakdown': 'Token 构成',
        'Prompt token caching': '提示词 Token 缓存',
        'Uncached': '未缓存',
        'Cached': '已缓存',
        'Median': '中位数',
        'Average': '平均值',
        'Range': '范围',
      },
      regexp: [],
      title: {
        static: {
          'Activity | OpenRouter': '活动记录 | OpenRouter',
        },
        regexp: [],
      },
    },

    /* ------------------------------ 日志 ------------------------------ */
    logs: {
      static: {
        'Generations': '生成记录',
        'Upstream Requests': '上游请求',
        'Sessions': '会话',
        'Videos': '视频',
        'Batches': '批处理',
        'App': '应用',
        'Usage Type': '用量类型',
        'Speed': '速度',
        'Routing Overhead': '路由开销',
        'Time to First Token': '首 Token 时间',
        'Finish Reason': '结束原因',
        'Report Feedback': '反馈问题',
        'Help us improve by reporting issues with this generation.': '通过报告本次生成的问题帮助我们改进。',
        'Generation ID': '生成 ID',
        'How to find your generation ID': '如何找到您的生成 ID',
        'Category': '类别',
        'Select a category': '选择一个类别',
        'Comment': '评论',
        'Generation details': '生成详情',
        'Input': '输入',
        'Output': '输出',
        'Provider': '提供商',
        'Model': '模型',
        'Date': '日期',
        'Cost': '费用',
      },
      regexp: [],
      title: {
        static: {
          'Logs | OpenRouter': '日志 | OpenRouter',
        },
        regexp: [],
      },
    },

    /* ------------------------------ 登录页 ------------------------------ */
    signin: {
      static: {
        'Use passkey instead': '改用密钥',
        'Don\u2019t have an account?': '没有账户?',
        'Have an account?': '已有账户?',
        'Continue with Google': '使用 Google 继续',
        'Continue with GitHub': '使用 GitHub 继续',
        'Continue with MetaMask': '使用 MetaMask 继续',
        'Create account': '创建账户',
        'Enter your email': '输入您的邮箱',
        'Enter your password': '输入您的密码',
        'Wrong email or password': '邮箱或密码错误',
        'Too many attempts. Please try again later.': '尝试次数过多，请稍后再试。',
      },
      regexp: [],
      title: {
        static: {
          'Sign In | OpenRouter': '登录 | OpenRouter',
          'Sign Up | OpenRouter': '注册 | OpenRouter',
          'Sign in | OpenRouter': '登录 | OpenRouter',
          'Sign up | OpenRouter': '注册 | OpenRouter',
        },
        regexp: [],
      },
    },

    /* ------------------------------ 博客 ------------------------------ */
    blog: {
      static: {
        'Announcements': '公告',
        'Tutorials': '教程',
        'Insights': '洞察',
        'Related Posts': '相关文章',
        'Share this post': '分享这篇文章',
        'Back to Blog': '返回博客',
      },
      regexp: [],
      title: {
        static: {},
        regexp: [],
      },
    },

    /* ------------------------------ 其他页面 ------------------------------ */
    misc: {
      static: {
        'Not Found': '未找到',
        'Go Home': '返回首页',
        'Page Not Found': '页面未找到',
        'The page you were looking for could not be found.': '您查找的页面不存在。',
        'About Us': '关于我们',
        'Terms': '条款',
        'Cookie Settings': 'Cookie 设置',
        'Trust Center': '信任中心',
        'Contact': '联系我们',
        'Contact us': '联系我们',
        'Help': '帮助',
        'FAQ': '常见问题',
        'Changelog': '更新日志',
        'Roadmap': '路线图',
      },
      regexp: [],
      title: {
        static: {},
        regexp: [],
      },
    },
  },
};
